# Generated by Django 3.2.16 on 2026-06-19 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gifts/')),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('experience', 'Experience'), ('home', 'Home'), ('honeymoon', 'Honeymoon'), ('cash', 'Cash fund'), ('charity', 'Charity'), ('other', 'Other')], default='other', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allow_partial', models.BooleanField(default=True)),
                ('is_cash_fund', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='registries.registry')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
