# Generated by Django 3.2.16 on 2026-06-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='category',
            field=models.CharField(choices=[('experience', 'Experience'), ('home', 'Home'), ('honeymoon', 'Honeymoon'), ('nursery', 'Nursery'), ('baby_essentials', 'Baby essentials'), ('education', 'Education fund'), ('party', 'Party'), ('memorial_fund', 'Memorial fund'), ('cash', 'Cash fund'), ('charity', 'Charity'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
