# Generated by Django 3.2.16 on 2026-06-21 15:06

from django.db import migrations, models
import gifts.models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_gift_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gifts.models.gift_upload_to),
        ),
    ]
