# Generated by Django 3.2.16 on 2026-06-21 20:32

from django.db import migrations, models
import gifts.models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_alter_gift_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=gifts.models.gift_upload_to),
        ),
    ]
