# Generated by Django 3.2.16 on 2026-06-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_alter_gift_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='show_progress',
            field=models.BooleanField(default=True),
        ),
    ]
