# Generated by Django 3.2.16 on 2026-06-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_gift_show_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='kind',
            field=models.CharField(choices=[('cash', 'Cash fund'), ('goal', 'Funding goal'), ('item', 'Specific item')], default='goal', max_length=10),
        ),
        migrations.AddField(
            model_name='gift',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='reserved_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='gift',
            name='reserved_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
