# Generated by Django 3.2.16 on 2026-06-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_contribution',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_rsvp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_product',
            field=models.BooleanField(default=True),
        ),
    ]
