# Generated by Django 3.2.16 on 2026-06-19 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('partner_one_name', models.CharField(max_length=80)),
                ('partner_two_name', models.CharField(max_length=80)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('cover_image_url', models.URLField(blank=True)),
                ('hero_message', models.CharField(blank=True, max_length=240)),
                ('our_story', models.TextField(blank=True)),
                ('show_story', models.BooleanField(default=True)),
                ('show_timeline', models.BooleanField(default=True)),
                ('show_gallery', models.BooleanField(default=True)),
                ('show_event_details', models.BooleanField(default=True)),
                ('show_registry', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('blush', 'Blush & Gold'), ('midnight', 'Midnight'), ('sage', 'Sage')], default='blush', max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=80)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'registries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='moments/')),
                ('image_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='registries.registry')),
            ],
            options={
                'ordering': ['sort_order', 'date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='registries.registry')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
