# Generated by Django 3.2.16 on 2026-06-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0002_registry_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby shower'), ('birthday', 'Birthday'), ('memorial', 'Memorial')], default='wedding', max_length=20),
        ),
        migrations.AddField(
            model_name='registry',
            name='organiser_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registry',
            name='show_tributes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='turning_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='years_celebrated',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='partner_two_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='registry',
            name='theme',
            field=models.CharField(choices=[('blush', 'Blush & Gold'), ('eternal', 'Eternal'), ('nursery', 'Nursery'), ('confetti', 'Confetti'), ('memorial', 'Memorial'), ('midnight', 'Midnight'), ('sage', 'Sage')], default='blush', max_length=20),
        ),
        migrations.CreateModel(
            name='Tribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributes', to='registries.registry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
