# Generated by Django 3.2.16 on 2026-06-21 15:06

from django.db import migrations, models
import registries.models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0003_auto_20260621_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=registries.models.gallery_upload_to),
        ),
        migrations.AlterField(
            model_name='registry',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=registries.models.cover_upload_to),
        ),
        migrations.AlterField(
            model_name='storymoment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=registries.models.moment_upload_to),
        ),
    ]
