# Generated by Django 3.2.16 on 2026-06-21 17:09

import config.storages
from django.db import migrations, models
import django.db.models.deletion
import registries.models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0004_auto_20260621_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='guest_uploads_allow_video',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='show_guest_uploads',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='GuestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(storage=config.storages.guest_media_storage, upload_to=registries.models.guest_upload_to)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('uploader_name', models.CharField(blank=True, max_length=120)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_uploads', to='registries.registry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
