# Generated by Django 3.2.16 on 2026-06-21 20:32

import config.storages
from django.db import migrations, models
import registries.models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0005_auto_20260621_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=registries.models.gallery_upload_to),
        ),
        migrations.AlterField(
            model_name='guestupload',
            name='media',
            field=models.FileField(max_length=255, storage=config.storages.guest_media_storage, upload_to=registries.models.guest_upload_to),
        ),
        migrations.AlterField(
            model_name='registry',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=registries.models.cover_upload_to),
        ),
        migrations.AlterField(
            model_name='storymoment',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=registries.models.moment_upload_to),
        ),
    ]
