# Generated by Django 3.2.16 on 2026-06-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0009_registry_checkin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventguest',
            name='table',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='registry',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public — anyone with the link, listed publicly'), ('unlisted', 'Unlisted — anyone with the link, not listed'), ('invite_only', 'Invite only — only invited guests (via their link)')], default='public', max_length=12),
        ),
        migrations.AlterField(
            model_name='eventguest',
            name='rsvp_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('yes', 'Attending'), ('maybe', 'Maybe'), ('no', 'Declined')], default='pending', max_length=10),
        ),
    ]
