# Generated by Django 3.2.16 on 2026-06-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='thanked',
            field=models.BooleanField(default=False),
        ),
    ]
