# Generated by Django 3.2.16 on 2026-06-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_contribution_thanked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('queued', 'Queued'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='requested', max_length=12),
        ),
    ]
