# Generated by Django 3.2.16 on 2026-06-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_withdrawal_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='card_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contribution',
            name='fees_covered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contribution',
            name='show_amount',
            field=models.BooleanField(default=True),
        ),
    ]
